print("ENTER FIRST NUMBER")
a=input()
print("ENTER SECOND NUMBER")
b=input()
print("THE SUM OF TWO NUMBERS IS", int(a) + int(b))
print("THE SUBTRACTION OF TWO NUMBERS IS" , int(a) - int(b))
print("THE MULTIPLICATION OF TWO NUMBERS IS" , int(a) * int(b))
print("THE DIVISION OF TWO NUMBERS IS" , int(a) / int(b))